### PR TITLE
Reversing init assignments

### PR DESCRIPTION
**Pull request by michaelaye**
This provides availability of the cell description, then provided to the pytest.Item constructor.

### CODE REVIEW

**Comment by michaelaye** [comment]
Works fine here!
```bash
test_spicer.ipynb::setup PASSED
test_spicer.ipynb::test spicer time init PASSED
test_spicer.ipynb::test illum angles PASSED
test_spicer.ipynb::test illum angles from tuples PASSED
test_spicer.ipynb::test coords PASSED
test_spicer.ipynb::test spicer time init PASSED
test_spicer.ipynb::test spicer target id PASSED
test_spicer.ipynb::test spicer target id failure PASSED
test_spicer.ipynb::test spicer radii PASSED
test_spicer.ipynb::test spicer center to sun PASSED
test_spicer.ipynb::test spicer solar constant PASSED
test_spicer.ipynb::test spicer srfrec body none PASSED
test_spicer.ipynb::test spicer srfrec body sun PASSED
test_spicer.ipynb::test spicer set spoint by latlon PASSED
test_spicer.ipynb::test spoint func not supported PASSED
test_spicer.ipynb::test spoint func not yet implemented PASSED
test_spicer.ipynb::test spoint lat not given PASSED
test_spicer.ipynb::test spoint lon not given PASSED
test_spicer.ipynb::no description PASSED
```

**Comment by zonca** [comment]
@michaelaye I think 1e32d1c1592d041216e0bf2daead836d42e2f9dd in #11 was enough,
can you explain why you need also to reverse the init assignments?

also can you please separate PEP8 from the other changes in  dabfda4 ? otherwise it is difficult to understand what you are doing.

**Comment by michaelaye** [comment]
I did this fix before I saw #11 . And while I first thought my output was prettier, you version is more informative, citing the cell number. Closing.

**Comment by michaelaye** [comment]
I just noticed, unfortunately too late, that your solution does not plot the test names at all!?
```bash
plugins: ipynb-1.0.2
collected 21 items

test_clustering.ipynb::notebooks/tests/test_clustering.ipynb PASSED
test_clustering.ipynb::notebooks/tests/test_clustering.ipynb PASSED
```

**Comment by michaelaye** [comment]
Ah no, all is fine, i had an old stuck installation somehow...

**Pull request closed without merging**
